### ISSUE TITLE
Doesnt work anymore in the RoR2 Artifact Update

### ISSUE THREAD

**Issue by xiaoxiao921** [Melledy/RoR2-PlayerBots#10]
https://cdn.discordapp.com/attachments/562711077453037589/696516446058184734/unknown.png

it rely on the GetPlayerCountInRadius, but that method moved to HoldoutZoneController.CountPlayersInRadius

**Comment by harbingerofme** [comment]
This is a **deprecation** notice. Your mod has been deprecated from thunderstore until you can get around to fix the issue. Undeprecating is easy, just push an update, easy as that.

**Comment by weeb420** [comment]
i have never done anything related to coding and dont know how to push a update any help will be appreciated

**Comment by Melledy** [comment]
My mod is updated now, thank you for the notification.
