### ISSUE TITLE
Incompatible with Anniversary update

### ISSUE THREAD

**Issue by bable631** [Melledy/RoR2-PlayerBots#13]
I have this installed via the Thunderstore Mod Manager, and I have all of the survivors set to spawn at the start of each run in the config. None of them do, but if I set them to spawn as players, the Commando shows up of the left hand side, dead. He never actually spawns. Is this mod going to be updated to fix this?

**Comment by KingKannibal** [comment]
I'd like to also know if there is a possibility of an update for this mod. Did not realize it was an anniversary update incompatibility. I ran this mod by itself and I get an error. Can update with the error I get when I get a chance to play again.

**Comment by Melledy** [comment]
Will be updated soon 🙂
