### ISSUE TITLE
[Suggestion] Revive fallen bots after each wave in Simulacrum Mode 

### ISSUE THREAD

**Issue by Fenlas** [Melledy/RoR2-PlayerBots#21]
In the Simulacrum gamemode, consider adding a respawn functionality for fallen bots during wave transitions. Instead of having to clear ten waves to progress towards next stage for bots to revive.

Otherwise, awesome job on this mod!

**Comment by Melledy** [comment]
Added in 155dbbbacbad4ed016753c69ec70c8992cef45e
