### ISSUE TITLE
Can't spawn bots

### ISSUE THREAD

**Issue by JenovaR** [Melledy/RoR2-PlayerBots#3]
I've tried this every way i can think of and it doesnt work. Single/multi/with friends/without - no bots. I cant access console because my pc doesnt have a tilde and when I try to remap my keyboard it still doesnt think its a real tilde button. I've lost half a day to this mod and I could cry. Is there any other way to open console? Thanks

**Comment by Melledy** [comment]
Open up the mod config (`com.meledy.PlayerBots.cfg`) in your config folder (`Risk of Rain 2\BepInEx\config`) and there should be some config values to set the amount of bots you start a run with.
