### ISSUE TITLE
Possible performance issue?

### ISSUE THREAD

**Issue by BlindOptometrist** [Melledy/RoR2-PlayerBots#4]
I've noticed the console is flooded with 

InvalidOperationExcepton: Cannot call Choose[] without available choices

after the bots buy their items. I'm getting fps issues on level one, which is very strange to me. never had fps issues, even in later levels. The bots also don't buy anymore items, even when I set the amount to higher values in the config, or set it in the console. let me know if you need anymore information, but it could just be me in the end :s

**Comment by Melledy** [comment]
You probably have an incompatible mod, probably one that messes with the drop table. Try removing all your mods except playerbots and see if you still get that error after the bots buy something.

**Comment by BlindOptometrist** [comment]
Quite funny, actually. I added a mod, and it stopped the flood. The mod I added does mess with the drop table, but prior to that, I had none. I did notice when the flooding stopped, performance increased. Also funny, the mod was "FloodWarning"
