### ISSUE TITLE
Can't spawn Engineer

### ISSUE THREAD

**Issue by Rachiou** [Melledy/RoR2-PlayerBots#5]
Whenever I would attempt via the config to spawn an engineer or the console to start off with one, it would basically wipe out whatever I previous tried to start with

Spawning with anything else seems to be fine otherwise. Thought it would be perfect to let you know I'm having an issue and if you needed anything more than me just putting this info out there.

Everything else works as expected otherwise (however I have not tried Rex if you did added him or bandit.)

**Comment by Melledy** [comment]
You might have an incompatibility issue with one of your other mods.
