### ISSUE TITLE
Bots not spawning on next stage

### ISSUE THREAD

**Issue by sidhepock** [Melledy/RoR2-PlayerBots#6]
Bots aren't spawning on subsequent stages. This applies to bots set to spawn at start, bots spawned mid-run, bots set as players, and bots set as summons. 

"Player" bots remain on the scoreboard and still affect scaling, even when not spawning.

**Comment by sidhepock** [comment]
Correction:
Bots that are set as **summons** WILL spawn on subsequent stages. My apologies.

**Comment by Melledy** [comment]
It works for me when i have bots set to players, make sure you dont have any mod conflicts, specifically ones that mess with stage loading in any way.
