### ISSUE TITLE
Bots only use primary attack and act oddly due to latest update to RoR2

### ISSUE THREAD

**Issue by sleepyal** [Melledy/RoR2-PlayerBots#8]
Error in BepInEx on game launch:
```
[Error  : Unity Log] MissingFieldException: Field 'RoR2.SurvivorDef.survivorIndex' not found.
Stack trace:
PlayerBots.AI.AiSkillHelperCatalog.RegisterSkillHelper (PlayerBots.AI.AiSkillHelper skillHelper) (at <ffaf3b080ad0407fa3790649f6c46d9a>:0)
PlayerBots.AI.AiSkillHelperCatalog.Populate () (at <ffaf3b080ad0407fa3790649f6c46
```

When in game, bots such as Loader and Mercenary will not close distance to attack and will slash the air at mid-range. All bots will not use any skill besides their primary fire. 

I'm assuming the issue is due to the latest update that changed the SurvivorAPI, and the code in PlayerBots to give each bot their relevant AI helper is not working correctly as it cannot query the list of survivors.

**Comment by Melledy** [comment]
Should be fixed as of the latest playerbots version.
